### ISSUE TITLE
gr-satellites not appearing on cgran.org

### ISSUE THREAD

**Issue by daniestevez** [gnuradio/gr-etcetera#55]
I have just noted that gr-satellites doesn't appear in cgran.org. However,the PyBOMBS recipe is in gr-etcetera. I was wondering if there is something wrong with the recipe.

**Comment by 777arc** [comment]
Ah thanks for pointing this out, when I was parsing recipes I was looking at the "source" field and then looking for the .git at the end, and it looks like gr-satellites and some others left off the .git from the url.  I'll edit the parsing script now to pick up those urls that leave off .git, and then when cgran.org refreshes it should show up.

**Comment by 777arc** [comment]
done!
